import React from 'react'
import './BeneficiariesTable.css'
import edit from '../../../assets/icons/edit.svg'

function Tbody({data}) {
    return (
        <>
            <td className='edit-button'>{/*edit*/}
                <img src={edit} alt="Editar" />
            </td>
            <td>
                {data.numDoc}
            </td>
            <td>
                {data.curState}
            </td>
            <td>
                {data.joinDate}
            </td>
            <td>
                {data.exitDate}
            </td>
            <td>
                {data.enterBy}
            </td>
            <td>
                {data.reasonForExit}
            </td>
            <td>
                {data.otherExitReason}
            </td>
            <td>
                {data.unitId}
            </td>
            <td>
                {data.duoId}
            </td>
            <td>
                {`${data.TeacherId[0]}, ${data.TeacherId[1]}`}
            </td>
            <td>
                {data.documentType}
            </td>
            <td>
                {data.firstName}
            </td>
            <td>
                {data.secondName}
            </td>
            <td>
                {data.firstLastName}
            </td>
            <td>
                {data.secondtLastName}
            </td>
            <td>
                {data.fullName}
            </td>
            <td>
                {data.birthDate}
            </td>
            <td>
                {data.years}
            </td>
            <td>
                {data.months}
            </td>
            <td>
                {data.days}
            </td>
            <td>
                {data.age}
            </td>
            <td>
                {data.beneficiaryType}
            </td>
            <td>
                {data.gender}
            </td>
            <td>
                {data.birthCountry}
            </td>
            <td>
                {data.birthDepartment}
            </td>
            <td>
                {data.birthMunicipality}
            </td>
            <td>
                {data.disability}
            </td>
            <td>
                {data.certifiedDisability}
            </td>
            <td>
                {data.entityCertifiesDisability}
            </td>
            <td>
                {data.disabilityCategory}
            </td>
            <td>
                {data.specifiedDisability}
            </td>
            <td>
                {data.disabilityRegistryEnrollment}
            </td>
            <td>
                {data.requiresAssistance}
            </td>
            <td>
                {data.requiresTechSupport}
            </td>
            <td>
                {data.hasTechSupport}
            </td>
            <td>
                {data.requiresTherapy}
            </td>
            <td>
                {data.receivesTherapy}
            </td>
            <td>
                {data.hasInterdictionProces}
            </td>
            <td>
                {data.countryOfResidence}
            </td>
            <td>
                {data.residenceDepartment}
            </td>
            <td>
                {data.locationZone}
            </td>
            <td>
                {data.locationType}
            </td>
            <td>
                {data.localityName}
            </td>
            <td>
                {data.neighborhood}
            </td>
            <td>
                {data.otherZone}
            </td>
            <td>
                {data.address}
            </td>
            <td>
                {data.primaryPhone}
            </td>
            <td>
                {data.secundaryPhone}
            </td>
            <td>
                {data.householdStratum}
            </td>
            <td>
                {data.groupEthnicity}
            </td>
            <td>
                {data.beneficiarySisbenized}
            </td>
            <td>
                {data.sisbenScore}
            </td>
            <td>
                {data.belongsToFamiliesInAction}
            </td>
            <td>
                {data.directlyAffectedByArmedConflict}
            </td>
            <td>
                {data.focusingCriteria}
            </td>
            <td>
                {data.justificationDocumentExists}
            </td>
            <td>
                {data.responsiblePersonType}
            </td>
            <td>
                {data.guardianDocumentType}
            </td>
            <td>
                {data.guardianDocumentNumber}
            </td>
            <td>
                {data.guardianFirstName}
            </td>
            <td>
                {data.guardianSecondName}
            </td>
            <td>
                {data.guardianFirstSurname}
            </td>
            <td>
                {data.guardianSecondSurname}
            </td>
            <td>
                {data.guardianBirthdate}
            </td>
            <td>
                {data.guardianBirthCountry}
            </td>
            <td>
                {data.guardianBirthDepartment}
            </td>
            <td>
                {data.guardianBirthCity}
            </td>
            <td>
                {data.fatherDocumentType}
            </td>
            <td>
                {data.fatherDocumentNumber}
            </td>
            <td>
                {data.fatherFirstName}
            </td>
            <td>
                {data.fatherSecondName}
            </td>
            <td>
                {data.fatherFirstSurname}
            </td>
            <td>
                {data.fatherSecondSurname}
            </td>
            <td>
                {data.fatherBirthdate}
            </td>
            <td>
                {data.fatherAge}
            </td>
            <td>
                {data.fatherBirthCountry}
            </td>
            <td>
                {data.fatherBirthDepartment}
            </td>
            <td>
                {data.fatherBirthCity}
            </td>
            <td>
                {data.motherDocumentType}
            </td>
            <td>
                {data.motherDocumentNumber}
            </td>
            <td>
                {data.motherFirstName}
            </td>
            <td>
                {data.motherSecondName}
            </td>
            <td>
                {data.motherFirstSurname}
            </td>
            <td>
                {data.motherSecondSurname}
            </td>
            <td>
                {data.motherBirthdate}
            </td>
            <td>
                {data.motherAge}
            </td>
            <td>
                {data.motherBirthCountry}
            </td>
            <td>
                {data.motherBirthDepartment}
            </td>
            <td>
                {data.motherBirthCity}
            </td>
            <td>
                {data.regime}
            </td>
            <td>
                {data.eps}
            </td>
            <td>
                {data.hasVaccinationCard}
            </td>
            <td>
                {data.vaccinationVerificationDate}
            </td>
            <td>
                {data.vaccinationCardUpToDate}
            </td>
            <td>
                {data.hasGrowthAndDevelopmentCard}
            </td>
            <td>
                {data.growthDevelopmentControlsReceived}
            </td>
            <td>
                {data.prematurenessBackground}
            </td>
            <td>
                {data.under40Weeks}
            </td>
            <td>
                {data.celiacProfile}
            </td>
            <td>
                {data.gestationalAgeAtBirth}
            </td>
            <td>
                {data.weightAtBirth}
            </td>
            <td>
                {data.heightAtBirth}
            </td>
            <td>
                {data.exclusivelyBreastfed}
            </td>
            <td>
                {data.exclusiveBreastfeedingDuration}
            </td>
            <td>
                {data.totalBreastfeedingDuration}
            </td>
            <td>
                {data.x}
            </td>
            <td>
                {data.beneficiaryType}
            </td>
            <td>
                {data.ticketNumber}
            </td>
        </>
    )
}

export default Tbody