const bene =[{
    numDoc: 1211111111, 
    curState: 'INACTIVO', 
    joinDate: '2000-02-29', 
    exitDate: null, 
    enterBy: 'DIEGo RODRIGUEZ', 
    reasonForExit: null, 
    otherExitReason: null,
    unitId: 'EL UVAL',
    duoId: 'OTRO',
    TeacherId: ['JOSEFA MARTINEZ', 'HERNAN HERNANDEZ'], 
    documentType: 'CC',  
    firstName: 'JUAN',
    secondName: 'DAVID',  
    firstLastName: 'RODRIGUEZ',
    secondtLastName: 'AMAYA', 
    fullName: 'JOSE DAVID RODRIGUEZ SALAZAR',
    birthDate: '2000-03-22', 
    years: 22, 
    months: 8, 
    days:  30,
    age: '22 AÑOS 8 MESES 30 DIAS',
    beneficiaryType: 'NIÑO O NIÑA ENTRE 6 MESES Y 5 AÑOS Y 11 MESES', 
    gender: 'FEMENINO',
    birthCountry: 'COLOMBIA',
    birthDepartment: 'BOGOTÁ',
    birthMunicipality:'BOGOTÁ',
    disability: 'NO_',
    certifiedDisability: 'NO_',    
    entityCertifiesDisability: '',
    disabilityCategory: 'NINGUNA', 
    specifiedDisability: '', 
    disabilityRegistryEnrollment: 'NO_', 
    requiresAssistance: 'NO_', 
    requiresTechSupport: 'NO',
    hasTechSupport: 'NO',
    requiresTherapy: 'NO_', 
    receivesTherapy: 'NO_',
    hasInterdictionProces: 'NO_',
    countryOfResidence: 'COLOMBIA',
    residenceDepartment: 'BOGOTÁ',
    locationZone: 'CABECERA',
    locationType: 'LOCALIDAD',
    localityName: 'USME',
    neighborhood: 'PUERTA AL LLANO',
    otherZone: 'PUERTA AL LLANO',
    address: 'CARRERA 7C ESTE 107 SUR 39',
    primaryPhone: 3203187736,
    secundaryPhone: null,
    householdStratum: 1,
    groupEthnicity: 'NO SE AUTORECONOCE EN NINGUNO DE LOS ANTERIORES',
    beneficiarySisbenized: 'SI_',
    sisbenScore: 'C6',
    belongsToFamiliesInAction: 'NO_',
    directlyAffectedByArmedConflict: 'NO_',
    focusingCriteria: 'F. VÍCTIMAS DE HECHOS VIOLENTOS ASOCIADOS AL CONFLICTO ARMADO, DE ACUERDO CON LAS DIRECTRICES ESTABLECIDAS EN LA LEY 1448 DE 2011 Y LOS DECRETOS LEY 4633, 4634 Y 4635 DE 2011, ASÍ COMO LA SENTENCIA T-025 DE 2004 PROFERIDA POR LA CORTE CONSTITUCIONAL Y DEMÁS DESARROLLOS JURISPRUDENCIALES EN TORNO A LA EXISTENCIA DE UN ESTADO DE COSAS INCONSTITUCIONAL; PARA LO CUAL SE CONSIDERARÁN AQUELLOS CUYO ESTADO SE ENCUENTRE INCLUIDO DENTRO DEL RUV.',
    justificationDocumentExists: null, 
    responsiblePersonType: 'MADRE',
    guardianDocumentType: 'CC',
    guardianDocumentNumber: 1014027273,
    guardianFirstName: 'CLAUDIA',
    guardianSecondName: 'PATRICIA',
    guardianFirstSurname: 'MONSALVE',
    guardianSecondSurname: 'LEON',
    guardianBirthdate: '1989-08-30',
    guardianBirthCountry: 'COLOMBIA',
    guardianBirthDepartment: 'BOGOTÁ',
    guardianBirthCity: 'BOGOTÁ',
    fatherDocumentType:'CC',
    fatherDocumentNumber: 1023034116,
    fatherFirstName: 'ANDRES',
    fatherSecondName: 'FELIPE',
    fatherFirstSurname: 'MEDINA',
    fatherSecondSurname: 'PORRAS',
    fatherBirthdate: '1949-01-20',
    fatherAge:80,
    fatherBirthCountry: 'COLOMBIA',
    fatherBirthDepartment: 'BOGOTÁ',
    fatherBirthCity: 'BOGOTÁ',
    motherDocumentType: 'CC',
    motherDocumentNumber: 1023004072,
    motherFirstName: 'CLAUDIA',
    motherSecondName: 'PATRICIA',
    motherFirstSurname: 'MONSALVE',
    motherSecondSurname: 'LEON',
    motherBirthdate: '1989-08-30',
    motherAge: 33,
    motherBirthCountry: 'COLOMBIA',
    motherBirthDepartment: 'BOGOTÁ',
    motherBirthCity: 'BOGOTÁ',
    regime: 'SUBSIDIADO',
    eps: 'NUEVA EPS',
    hasVaccinationCard: 'NO_',
    vaccinationVerificationDate: '2022-02-28',
    vaccinationCardUpToDate: 'NO_',
    hasGrowthAndDevelopmentCard: 'NO_', 
    growthDevelopmentControlsReceived: null, 
    prematurenessBackground: 'SI_',
    under40Weeks: 'NO_',
    celiacProfile: null, 
    gestationalAgeAtBirth: 40, 
    weightAtBirth:  2240,
    heightAtBirth: 60,
    exclusivelyBreastfed: 'NO_',
    exclusiveBreastfeedingDuration: 5, 
    totalBreastfeedingDuration: 6,
    x: 'SEM 23',
    complementType: 'NIÑOS Y NIÑAS DE 6 MESES A 11 MESES 29 DIAS',
    ticketNumber: null
},
{
    numDoc: 1222112121, 
    curState: 'INACTIVO', 
    joinDate: '2000-02-29', 
    exitDate: null, 
    enterBy: 'DIEGO RODRIGUEZ', 
    reasonForExit: null, 
    otherExitReason: null,
    unitId: 'SERRANIAS',
    duoId: 'HILANDO CAMINOS',
    TeacherId: ['JOSEFA MARTINEZ', 'HERNAN HERNANDEZ'], 
    documentType: 'CC',  
    firstName: 'JUAN',
    secondName: 'DAVID',  
    firstLastName: 'RODRIGUEZ',
    secondtLastName: 'AMAYA', 
    fullName: 'JOSE DAVID RODRIGUEZ SALAZAR',
    birthDate: '2000-03-22', 
    years: 22, 
    months: 8, 
    days:  30,
    age: '22 AÑOS 8 MESES 30 DIAS',
    beneficiaryType: 'MUJER GESTANTE', 
    gender: 'FEMENINO',
    birthCountry: 'COLOMBIA',
    birthDepartment: 'BOGOTÁ',
    birthMunicipality:'BOGOTÁ',
    disability: 'NO_',
    certifiedDisability: 'NO_',    
    entityCertifiesDisability: '',
    disabilityCategory: 'NINGUNA', 
    specifiedDisability: '', 
    disabilityRegistryEnrollment: 'NO_', 
    requiresAssistance: 'NO_', 
    requiresTechSupport: 'NO',
    hasTechSupport: 'NO',
    requiresTherapy: 'NO_', 
    receivesTherapy: 'NO_',
    hasInterdictionProces: 'NO_',
    countryOfResidence: 'COLOMBIA',
    residenceDepartment: 'BOGOTÁ',
    locationZone: 'CABECERA',
    locationType: 'LOCALIDAD',
    localityName: 'USME',
    neighborhood: 'PUERTA AL LLANO',
    otherZone: 'PUERTA AL LLANO',
    address: 'CARRERA 7C ESTE 107 SUR 39',
    primaryPhone: 3203187736,
    secundaryPhone: null,
    householdStratum: 1,
    groupEthnicity: 'NO SE AUTORECONOCE EN NINGUNO DE LOS ANTERIORES',
    beneficiarySisbenized: 'SI_',
    sisbenScore: 'C6',
    belongsToFamiliesInAction: 'NO_',
    directlyAffectedByArmedConflict: 'NO_',
    focusingCriteria: 'A. PERTENECIENTES A HOGARES CON PUNTAJE SISBEN',
    justificationDocumentExists: null, 
    responsiblePersonType: 'MADRE',
    guardianDocumentType: 'CC',
    guardianDocumentNumber: 1014027273,
    guardianFirstName: 'CLAUDIA',
    guardianSecondName: 'PATRICIA',
    guardianFirstSurname: 'MONSALVE',
    guardianSecondSurname: 'LEON',
    guardianBirthdate: '1989-08-30',
    guardianBirthCountry: 'COLOMBIA',
    guardianBirthDepartment: 'BOGOTÁ',
    guardianBirthCity: 'BOGOTÁ',
    fatherDocumentType:'CC',
    fatherDocumentNumber: 1023034116,
    fatherFirstName: 'ANDRES',
    fatherSecondName: 'FELIPE',
    fatherFirstSurname: 'MEDINA',
    fatherSecondSurname: 'PORRAS',
    fatherBirthdate: '1949-01-20',
    fatherAge:80,
    fatherBirthCountry: 'COLOMBIA',
    fatherBirthDepartment: 'BOGOTÁ',
    fatherBirthCity: 'BOGOTÁ',
    motherDocumentType: 'CC',
    motherDocumentNumber: 1023004072,
    motherFirstName: 'CLAUDIA',
    motherSecondName: 'PATRICIA',
    motherFirstSurname: 'MONSALVE',
    motherSecondSurname: 'LEON',
    motherBirthdate: '1989-08-30',
    motherAge: 33,
    motherBirthCountry: 'COLOMBIA',
    motherBirthDepartment: 'BOGOTÁ',
    motherBirthCity: 'BOGOTÁ',
    regime: 'SUBSIDIADO',
    eps: 'NUEVA EPS',
    hasVaccinationCard: 'NO_',
    vaccinationVerificationDate: '2022-02-28',
    vaccinationCardUpToDate: 'NO_',
    hasGrowthAndDevelopmentCard: 'NO_', 
    growthDevelopmentControlsReceived: null, 
    prematurenessBackground: 'SI_',
    under40Weeks: 'NO_',
    celiacProfile: null, 
    gestationalAgeAtBirth: 40, 
    weightAtBirth:  2240,
    heightAtBirth: 60,
    exclusivelyBreastfed: 'NO_',
    exclusiveBreastfeedingDuration: 5, 
    totalBreastfeedingDuration: 6,
    x: 'SEM 23',
    complementType: 'NIÑOS Y NIÑAS DE 6 MESES A 11 MESES 29 DIAS',
    ticketNumber: null
}, {
    numDoc: 1000555388, 
    curState: 'ACTIVO', 
    joinDate: '2000-02-29', 
    exitDate: null, 
    enterBy: 'DIEGO RODRIGUEZ', 
    reasonForExit: null, 
    otherExitReason: null,
    unitId: 'SAN JUAN A',
    duoId: 'HILANDO CAMINOS',
    TeacherId: ['JOSEFA MARTINEZ', 'HERNAN HERNANDEZ'], 
    documentType: 'CC',  
    firstName: 'JUAN',
    secondName: 'DAVID',  
    firstLastName: 'RODRIGUEZ',
    secondtLastName: 'AMAYA', 
    fullName: 'JOSE DAVID RODRIGUEZ SALAZAR',
    birthDate: '2000-03-22', 
    years: 22, 
    months: 8, 
    days:  30,
    age: '22 AÑOS 8 MESES 30 DIAS',
    beneficiaryType: 'MENOR DE SEIS MESES', 
    gender: 'FEMENINO',
    birthCountry: 'COLOMBIA',
    birthDepartment: 'BOGOTÁ',
    birthMunicipality:'BOGOTÁ',
    disability: 'NO_',
    certifiedDisability: 'NO_',    
    entityCertifiesDisability: '',
    disabilityCategory: 'NINGUNA', 
    specifiedDisability: '', 
    disabilityRegistryEnrollment: 'NO_', 
    requiresAssistance: 'NO_', 
    requiresTechSupport: 'NO',
    hasTechSupport: 'NO',
    requiresTherapy: 'NO_', 
    receivesTherapy: 'NO_',
    hasInterdictionProces: 'NO_',
    countryOfResidence: 'COLOMBIA',
    residenceDepartment: 'BOGOTÁ',
    locationZone: 'CABECERA',
    locationType: 'LOCALIDAD',
    localityName: 'USME',
    neighborhood: 'PUERTA AL LLANO',
    otherZone: 'PUERTA AL LLANO',
    address: 'CARRERA 7C ESTE 107 SUR 39',
    primaryPhone: 3203187736,
    secundaryPhone: null,
    householdStratum: 1,
    groupEthnicity: 'NO SE AUTORECONOCE EN NINGUNO DE LOS ANTERIORES',
    beneficiarySisbenized: 'SI_',
    sisbenScore: 'C6',
    belongsToFamiliesInAction: 'NO_',
    directlyAffectedByArmedConflict: 'NO_',
    focusingCriteria: 'H. NIÑOS Y NIÑAS CON DISCAPACIDAD QUE REQUIEREN DIVERSOS TIPOS DE APOYO PARA SU PARTICIPACIÓN EFECTIVA Y QUE DEMANDAN ACOMPAÑAMIENTO EN LAS ACTIVIDADES DE CUIDADO; ASÍ COMO LOS QUE SEAN REMITIDOS POR LAS ENTIDADES DEL SNBF CON BASE EN EL REGISTRO PARA LA LOCALIZACIÓN Y CARACTERIZACIÓN DE PERSONAS CON DISCAPACIDAD DEL MINISTERIO DE SALUD Y PROTECCIÓN SOCIAL, COMO DE LOS COMITÉS TERRITORIALES Y LOCALES DE DISCAPACIDAD Y LAS ENTIDADES TERRITORIALES EN SALUD.',
    justificationDocumentExists: null, 
    responsiblePersonType: 'MADRE',
    guardianDocumentType: 'CC',
    guardianDocumentNumber: 1014027273,
    guardianFirstName: 'CLAUDIA',
    guardianSecondName: 'PATRICIA',
    guardianFirstSurname: 'MONSALVE',
    guardianSecondSurname: 'LEON',
    guardianBirthdate: '1989-08-30',
    guardianBirthCountry: 'COLOMBIA',
    guardianBirthDepartment: 'BOGOTÁ',
    guardianBirthCity: 'BOGOTÁ',
    fatherDocumentType:'CC',
    fatherDocumentNumber: 1023034116,
    fatherFirstName: 'ANDRES',
    fatherSecondName: 'FELIPE',
    fatherFirstSurname: 'MEDINA',
    fatherSecondSurname: 'PORRAS',
    fatherBirthdate: '1949-01-20',
    fatherAge:80,
    fatherBirthCountry: 'COLOMBIA',
    fatherBirthDepartment: 'BOGOTÁ',
    fatherBirthCity: 'BOGOTÁ',
    motherDocumentType: 'CC',
    motherDocumentNumber: 1023004072,
    motherFirstName: 'CLAUDIA',
    motherSecondName: 'PATRICIA',
    motherFirstSurname: 'MONSALVE',
    motherSecondSurname: 'LEON',
    motherBirthdate: '1989-08-30',
    motherAge: 33,
    motherBirthCountry: 'COLOMBIA',
    motherBirthDepartment: 'BOGOTÁ',
    motherBirthCity: 'BOGOTÁ',
    regime: 'SUBSIDIADO',
    eps: 'NUEVA EPS',
    hasVaccinationCard: 'NO_',
    vaccinationVerificationDate: '2022-02-28',
    vaccinationCardUpToDate: 'NO_',
    hasGrowthAndDevelopmentCard: 'NO_', 
    growthDevelopmentControlsReceived: null, 
    prematurenessBackground: 'SI_',
    under40Weeks: 'NO_',
    celiacProfile: null, 
    gestationalAgeAtBirth: 40, 
    weightAtBirth:  2240,
    heightAtBirth: 60,
    exclusivelyBreastfed: 'NO_',
    exclusiveBreastfeedingDuration: 5, 
    totalBreastfeedingDuration: 6,
    x: 'SEM 23',
    complementType: 'NIÑOS Y NIÑAS DE 6 MESES A 11 MESES 29 DIAS',
    ticketNumber: null
}, {
    numDoc: 13333333338, 
    curState: 'ACTIVO', 
    joinDate: '2000-02-29', 
    exitDate: null, 
    enterBy: 'DIEGO RODRIGUEZ', 
    reasonForExit: null, 
    otherExitReason: null,
    unitId: 'TRIANGULO',
    duoId: 'HILANDO CAMINOS',
    TeacherId: ['JOSEFA MARTINEZ', 'HERNAN HERNANDEZ'], 
    documentType: 'CC',  
    firstName: 'JUAN',
    secondName: 'DAVID',  
    firstLastName: 'RODRIGUEZ',
    secondtLastName: 'AMAYA', 
    fullName: 'JOSE DAVID RODRIGUEZ SALAZAR',
    birthDate: '2000-03-22', 
    years: 22, 
    months: 8, 
    days:  30,
    age: '22 AÑOS 8 MESES 30 DIAS',
    beneficiaryType: 'MUJER GESTANTE', 
    gender: 'FEMENINO',
    birthCountry: 'COLOMBIA',
    birthDepartment: 'BOGOTÁ',
    birthMunicipality:'BOGOTÁ',
    disability: 'NO_',
    certifiedDisability: 'NO_',    
    entityCertifiesDisability: '',
    disabilityCategory: 'NINGUNA', 
    specifiedDisability: '', 
    disabilityRegistryEnrollment: 'NO_', 
    requiresAssistance: 'NO_', 
    requiresTechSupport: 'NO',
    hasTechSupport: 'NO',
    requiresTherapy: 'NO_', 
    receivesTherapy: 'NO_',
    hasInterdictionProces: 'NO_',
    countryOfResidence: 'COLOMBIA',
    residenceDepartment: 'BOGOTÁ',
    locationZone: 'CABECERA',
    locationType: 'LOCALIDAD',
    localityName: 'USME',
    neighborhood: 'PUERTA AL LLANO',
    otherZone: 'PUERTA AL LLANO',
    address: 'CARRERA 7C ESTE 107 SUR 39',
    primaryPhone: 3203187736,
    secundaryPhone: null,
    householdStratum: 1,
    groupEthnicity: 'NO SE AUTORECONOCE EN NINGUNO DE LOS ANTERIORES',
    beneficiarySisbenized: 'SI_',
    sisbenScore: 'C6',
    belongsToFamiliesInAction: 'NO_',
    directlyAffectedByArmedConflict: 'NO_',
    focusingCriteria: 'K. POBLACIÓN MIGRANTE, REFUGIADA O APÁTRIDA QUE CUMPLA CON ALGUNA DE LAS SIGUIENTES CARACTERÍSTICAS: AUSENCIA DE VIVIENDA O CONDICIONES DE HACINAMIENTO, QUE NO CUENTEN CON ACCESO A SERVICIOS PÚBLICOS DOMICILIARIOS O QUE NO CUENTEN CON NINGÚN TIPO DE AFILIACIÓN AL SISTEMA GENERAL DE SEGURIDAD SOCIAL EN SALUD.',
    justificationDocumentExists: null, 
    responsiblePersonType: 'MADRE',
    guardianDocumentType: 'CC',
    guardianDocumentNumber: 1014027273,
    guardianFirstName: 'CLAUDIA',
    guardianSecondName: 'PATRICIA',
    guardianFirstSurname: 'MONSALVE',
    guardianSecondSurname: 'LEON',
    guardianBirthdate: '1989-08-30',
    guardianBirthCountry: 'COLOMBIA',
    guardianBirthDepartment: 'BOGOTÁ',
    guardianBirthCity: 'BOGOTÁ',
    fatherDocumentType:'CC',
    fatherDocumentNumber: 1023034116,
    fatherFirstName: 'ANDRES',
    fatherSecondName: 'FELIPE',
    fatherFirstSurname: 'MEDINA',
    fatherSecondSurname: 'PORRAS',
    fatherBirthdate: '1949-01-20',
    fatherAge:80,
    fatherBirthCountry: 'COLOMBIA',
    fatherBirthDepartment: 'BOGOTÁ',
    fatherBirthCity: 'BOGOTÁ',
    motherDocumentType: 'CC',
    motherDocumentNumber: 1023004072,
    motherFirstName: 'CLAUDIA',
    motherSecondName: 'PATRICIA',
    motherFirstSurname: 'MONSALVE',
    motherSecondSurname: 'LEON',
    motherBirthdate: '1989-08-30',
    motherAge: 33,
    motherBirthCountry: 'COLOMBIA',
    motherBirthDepartment: 'BOGOTÁ',
    motherBirthCity: 'BOGOTÁ',
    regime: 'SUBSIDIADO',
    eps: 'NUEVA EPS',
    hasVaccinationCard: 'NO_',
    vaccinationVerificationDate: '2022-02-28',
    vaccinationCardUpToDate: 'NO_',
    hasGrowthAndDevelopmentCard: 'NO_', 
    growthDevelopmentControlsReceived: null, 
    prematurenessBackground: 'SI_',
    under40Weeks: 'NO_',
    celiacProfile: null, 
    gestationalAgeAtBirth: 40, 
    weightAtBirth:  2240,
    heightAtBirth: 60,
    exclusivelyBreastfed: 'NO_',
    exclusiveBreastfeedingDuration: 5, 
    totalBreastfeedingDuration: 6,
    x: 'SEM 23',
    complementType: 'NIÑOS Y NIÑAS DE 6 MESES A 11 MESES 29 DIAS',
    ticketNumber: null
}]
export default bene