// ------------------------- addBeneficiariesSchema - We set some default values (Mostly used)
const addBeneficiariesSchema ={
    curState: 'ACTIVO',
    documentType: 'RC',
    gender: 'FEMENINO',
    birthCountry: 'COLOMBIA',
    birthDepartment: 'BOGOTÁ, D.C.',
    disability: 'NO',
    certifiedDisability: 'NO',
    disabilityCategory: 'NINGUNA', 
    disabilityRegistryEnrollment: 'NO', 
    requiresAssistance: 'NO', 
    requiresTechSupport: 'NO',
    hasTechSupport: 'NO',
    requiresTherapy: 'NO', 
    receivesTherapy: 'NO',
    hasInterdictionProcess: 'NO',
    countryOfResidence: 'COLOMBIA',
    residenceDepartment: 'BOGOTÁ, D.C.',
    locationZone: 'CABECERA',
    headerType: 'LOCALIDAD',
    householdStratum: 0,
    groupEthnicity: 'NO SE AUTORECONOCE EN NINGUNO DE LOS ANTERIORES',
    beneficiarySisbenized: 'NO',
    belongsToFamiliesInAction: 'NO',
    directlyAffectedByArmedConflict: 'NO',
    justificationDocumentExists: 'NO', 
    guardianPersonType: 'MADRE',
    guardianDocumentType: 'CC',
    guardianBirthCountry: 'COLOMBIA',
    guardianBirthDepartment: 'BOGOTÁ, D.C.',
    guardianBirthCity: 'BOGOTÁ, D.C.',
    regime: 'SUBSIDIADO',
    hasVaccinationCard: 'SI'
}
export default addBeneficiariesSchema